{% set name = "N2SNUserTools" %}
{% set version = "0.2.1" %}
{% set sha256 = "978890b66835c95e3dd6dd11852676117f4ec6acafe3a36e8e7571144786cf74" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ldap3
    - prettytable
    - configparser
    - python-gssapi

test:
  imports:
    - N2SNUserTools

about:
  home: https://github.com/nsls-ii/N2SNUserTools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: User tools for the NSLS-II Science Network
