{% set name = "N2SNUserTools" %}
{% set version = "0.3.0" %}
{% set sha256 = "210e37e4806527042b03d9ab16da5159b301394f1f29811138062a098a60ff8d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - n2sn_add_user = N2SNUserTools.cli:n2sn_add_user
    - n2sn_list_users = N2SNUserTools.cli:n2sn_list_users
    - n2sn_remove_user = N2SNUserTools.cli:n2sn_remove_user
    - n2sn_search_user = N2SNUserTools.cli:n2sn_search_user

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ldap3
    - prettytable
    - python-gssapi

test:
  imports:
    - N2SNUserTools

about:
  home: https://github.com/nsls-ii/N2SNUserTools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: User tools for the NSLS-II Science Network
