{% set name = "N2SNUserTools" %}
{% set version = "0.2.2" %}
{% set sha256 = "552556c1faf2e3975db79e528b6ace8b7ccc035a8674eeb736953edb56c617b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - n2sn_add_offline_user = N2SNUserTools.cli:n2sn_add_offline_user
    - n2sn_add_user = N2SNUserTools.cli:n2sn_add_user
    - n2sn_list_offline_users = N2SNUserTools.cli:n2sn_list_offline_users
    - n2sn_list_staff = N2SNUserTools.cli:n2sn_list_staff
    - n2sn_list_users = N2SNUserTools.cli:n2sn_list_users
    - n2sn_remove_offline_user = N2SNUserTools.cli:n2sn_remove_offline_user
    - n2sn_remove_user = N2SNUserTools.cli:n2sn_remove_user
    - n2sn_search_user = N2SNUserTools.cli:n2sn_search_user

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ldap3
    - prettytable
    - configparser
    - python-gssapi

test:
  imports:
    - N2SNUserTools

about:
  home: https://github.com/nsls-ii/N2SNUserTools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: User tools for the NSLS-II Science Network
