{% set name = "N2SNUserTools" %}
{% set version = "0.2" %}
{% set sha256 = "10dc73dde516df064e0aa9eb915cffe6e77243584b9a2a1e5bb682e85e7bb3cd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ldap3
    - prettytable
    - configparser
    - gssapi

test:
  imports:
    - N2SNUserTools

about:
  home: https://github.com/nsls-ii/N2SNUserTools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: User tools for the NSLS-II Science Networki
